// export const thanks: Array<{ name: string, link?: string }> = [
//   { name: '立音喵' },
//   { name: 'lgd_小翅膀' },
//   { name: '青葉' },
//   { name: 'kn' },
//   { name: 'F74nk', link: 'https://t.me/F74nk_K' },
//   { name: '杨佳文' },
//   { name: '不知名的N姓人士就好' },
//   { name: '某不愿透露姓名的N性？' },
//   { name: '神楽坂 萌绫' },
//   { name: 'Butby' },
//   { name: 'NekoCaffeine' },
//   { name: 'RainSlide' },
//   { name: 'czp', link: 'https://www.hiczp.com' },
//   { name: 'kookxiang' },
//   { name: '櫻川 紗良' },
//   { name: 'Skimige' },
//   { name: 'TExL', link: 'http://texas.penguin-logistics.cn' },
//   { name: '路人乙' },
//   { name: 'pokemonchw', link: 'https://github.com/pokemonchw' },
//   { name: '帕蒂卡', link: 'https://github.com/Patika-ailemait' },
//   { name: '零件', link: 'https://nekosc.com' },
//   { name: '幻梦', link: 'https://t.me/HuanmengQwQ' },
//   { name: 'acted咕咕喵', link: 'https://acted.gitlab.io/h3' },
//   { name: '重水时雨', link: 'https://t.me/boatmasteronD2O' },
//   { name: '神楽坂 紫' },
//   { name: 'Runian Lee', link: 'https://t.me/Runian' },
//   { name: '琥珀' },
//   { name: '为霜' },
//   { name: '冰蓮音' },
//   { name: 'Testingdoll01' },
//   { name: 'VV', link: 'https://www.pixiv.net/users/58170013' },
//   { name: '城岭 樱' },
//   { name: '熵' },
//   { name: '0 级骨钉' },
//   { name: '夏克斯' },
//   { name: '王木木' },
//   { name: 'C86', link: 'https://c86.moe' },
//   { name: '炽羽渡尘01' },
//   { name: '47AD' },
//   { name: '禾裱禾裱' },
//   { name: '灵翼' },
//   { name: '铱则' },
// ].sort(() => Math.random() - 0.5);
